# Override default values in the Apache Airflow Helm Chart
#
defaultAirflowTag: "3.0.3"
airflowVersion: "3.0.3"

# 4 - Dags baked inside custom image
images:
  airflow:
    repository: registry:5000/manning-airflow/my-airflow
    tag: k8s
    pullPolicy: Always

# 3 - Using the external database
postgres:
  enabled: false

data:
  metadataSecretName: mydatabase

# 2 - Overriding the api secret reference
apiSecretKeySecretName: my-apiserver-secret
webserverSecretKeySecretName: my-apiserver-secret

# 1 - Overriding the default user since we use a different database
webserver:
  # Create initial user.
  defaultUser:
    enabled: true
    role: Admin
    username: airflow
    email: airflow@example.com
    firstName: Airflow
    lastName: Second Edition
    password: airflow
