# Override default values in the Apache Airflow Helm Chart
#
# 4/5 - Dags and dependencies baked inside custom image
images:
  airflow:
    repository: registry:5000/manning-airflow/airflow-deps
    tag: k8s
    pullPolicy: Always

# 3 - Using the external database
postgres:
  enabled: false

data:
  metadataSecretName: mydatabase

# 2 - Overriding the webserver secret reference
webserverSecretKeySecretName: my-webserver-secret

# 1 - Overriding the default user since we use a different database
webserver:
  # Create initial user.
  defaultUser:
    enabled: true
    role: Admin
    username: airflow
    email: airflow@example.com
    firstName: Airflow
    lastName: Second Edition
    password: airflow
