# Override default values in the Apache Airflow Helm Chart
#
# 6 - Multiple executors
executor: "CeleryExecutor,KubernetesExecutor"
config:
  kubernetes:
    worker_container_repository: '' # Needs to be empty to be overrided via pod_template_file
    worker_container_tag: '' # Needs to be empty to be overrided via pod_template_file
  kubernetes_executor:
    worker_container_repository: '' # Needs to be empty to be overrided via pod_template_file
    worker_container_tag: '' # Needs to be empty to be overrided via pod_template_file

# podTemplate: |
#   {{ tpl ($.Files.Get "/etc/helm/values/pod_template_default_override.yaml") . | nindent 4 }}

# 4/5 - Dags and dependencies baked inside custom image
images:
  airflow:
    repository: registry:5000/manning-airflow/airflow-executors
    tag: k8s
    pullPolicy: Always
  pod_template:
    repository: registry:5000/manning-airflow/airflow-executors-deps
    tag: k8s
    pullPolicy: Always

# 3 - Using the external database
postgres:
  enabled: false

data:
  metadataSecretName: mydatabase

# 2 - Overriding the webserver secret reference
webserverSecretKeySecretName: my-webserver-secret

# 1 - Overriding the default user since we use a different database
webserver:
  # Create initial user.
  defaultUser:
    enabled: true
    role: Admin
    username: airflow
    email: airflow@example.com
    firstName: Airflow
    lastName: Second Edition
    password: airflow
