x-airflow-common:
  &airflow-common
  environment:
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL : 60
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__TEST_CONNECTION: "Enabled"
    AIRFLOW__DAG_PROCESSOR__REFRESH_INTERVAL: 60
    AIRFLOW__API_AUTH__JWT_SECRET: foo
    AIRFLOW__API__SECRET_KEY: bar

services:
  airflow-apiserver:
    <<: *airflow-common

  airflow-dag-processor:
    <<: *airflow-common

  airflow-scheduler:
    <<: *airflow-common

  airflow-worker:
    <<: *airflow-common

  airflow-triggerer:
    <<: *airflow-common

  airflow-init:
    <<: *airflow-common
    environment:
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: ""
      _AIRFLOW_WWW_USER_USERNAME: ""
      _AIRFLOW_WWW_USER_PASSWORD: ""
      _PIP_ADDITIONAL_REQUIREMENTS: ""


  airflow-cli:
    <<: *airflow-common
