FROM apache/airflow:2.10.2

COPY requirements.txt /opt/airflow/requirements.txt

USER root

RUN apt-get update && \
 apt-get install -y gcc && \
 apt-get autoremove -y && \
 apt-get clean -y && \
 rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --user -r /opt/airflow/requirements.txt && rm /opt/airflow/requirements.txt
