# Override default values in the Apache Airflow Helm Chart
#
defaultAirflowTag: "3.0.6"
airflowVersion: "3.0.6"

# 2 - Overriding the api secret reference
apiSecretKeySecretName: my-apiserver-secret
webserverSecretKeySecretName: my-webserver-secret
