kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-path-dag-volume
  namespace: airflow
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-path-dag-volume-claim
  namespace: airflow
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
