x-airflow-common:
  &airflow-common
  environment:
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL : 60
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__TEST_CONNECTION: "Enabled"
    AIRFLOW__DAG_PROCESSOR__REFRESH_INTERVAL: 60
    AIRFLOW__API_AUTH__JWT_SECRET: foo
    AIRFLOW__API__SECRET_KEY: bar
    AIRFLOW__SECRETS__BACKEND: airflow.providers.hashicorp.secrets.vault.VaultBackend
    AIRFLOW__SECRETS__BACKEND_KWARGS: '{"url":"http://vault:8200","token":"airflow","connections_path":"connections","variables_path": "variables"}'

services:
  airflow-apiserver:
    <<: *airflow-common

  airflow-dag-processor:
    <<: *airflow-common

  airflow-scheduler:
    <<: *airflow-common

  airflow-worker:
    <<: *airflow-common

  airflow-triggerer:
    <<: *airflow-common

  airflow-init:
    <<: *airflow-common

  airflow-cli:
    <<: *airflow-common

  vault:
    image: hashicorp/vault:1.20
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=airflow
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault_config/:/vault/config.d/

  secure_api:
    build: ./secure_api
    ports:
      - "5000:5000"

