---
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      PGUSER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  k3s-server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: 
    - server
    - "--tls-san"
    - "k3s-server"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_NODE_NAME=k3s-server
    - K3S_TOKEN=26576147927211
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .k3s:/output
    - .registryconfig/registries.yaml:/etc/rancher/k3s/registries.yaml
    - ./dags-pvc:/data
    ports:
    - 6443:6443  # Kubernetes API Server
    - 80:80      # Ingress controller port 80
    - 443:443    # Ingress controller port 443
    - 8080:8080  # Airflow web UI

  k3s-agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_NODE_NAME=k3s-agent
    - K3S_URL=https://k3s-server:6443
    - K3S_TOKEN=26576147927211
    ports:
    - 8081:8080  # Airflow web UI if loadbalancer is on agent server
    volumes:
    - .registryconfig/registries.yaml:/etc/rancher/k3s/registries.yaml
    - ./dags-pvc-agent:/data

  k3s-cli:
    image: alpine/k8s:1.32.0
    tty: true
    privileged: true
    environment:
    - KUBECONFIG=/input/kubeconfig.yaml
    volumes:
    - .k3s:/input
    - ./enable-external-dns.sh:/enable-external-dns
    - ./bash_aliases.sh:/etc/profile.d/bash_aliases.sh
    - ./values:/etc/helm/values

  registry:
    image: registry:2
    ports:
      - 3632:5000
    volumes:
      - container-registry-volume:/var/lib/registry

volumes:
  k3s-server:
  postgres-db-volume:
  container-registry-volume:
